# Valid TOML config file
genesis-file="./genesis.json"
data-path="./data"
host-allowlist=["*"]
min-gas-price=0

# Peers
p2p-port=30000
host="0.0.0.0"  # Escucha en todas las interfaces
max-peers=42

# Mining
miner-enabled=true
miner-coinbase="0x23d2B00318eD562931614edc6fCF1B5bF239a2a6"

# RPC HTTP
rpc-http-enabled=true
rpc-http-host="0.0.0.0"  # Escucha en todas las interfaces para RPC
rpc-http-port=8540
rpc-http-cors-origins=["*"]
rpc-http-api=['ADMIN', 'ETH', 'NET', 'WEB3', 'CLIQUE', 'IBFT', 'PERM', 'DEBUG', 'MINER', 'EEA', 'PRIV', 'TXPOOL']

# RPC WebSocket
rpc-ws-enabled=true
rpc-ws-port=6174
rpc-ws-api=['ADMIN', 'ETH', 'NET', 'WEB3', 'CLIQUE', 'IBFT', 'PERM', 'DEBUG', 'MINER', 'EEA', 'PRIV', 'TXPOOL']

# Permissions
permissions-nodes-config-file-enabled=true
permissions-accounts-config-file-enabled=true
permissions-nodes-config-file="./data/permissions_config.toml"
permissions-accounts-config-file="./data/permissions_config.toml"
