apiVersion: v1
kind: ConfigMap
metadata:
  name: genesis-config-files
  namespace: besu-network
data:
  initialGenesis.json: |
    {
        "genesis": {
            "config": {
                "chainId": 1337,
                "berlinBlock": 0,
                "contractSizeLimit": 5242880,
                "ibft2": {
                    "blockperiodseconds": 2,
                    "epochlength": 30000,
                    "requesttimeoutseconds": 4
                }
            },
            "nonce": "0x0",
            "timestamp": "0x58ee40ba",
            "gasLimit": "0x6691B7",
          "difficulty": "0x1",

            "mixHash": "0x63746963616c2062797a616e74696e65206661756c7420746f6c6572616e6365",
            "coinbase": "0x0000000000000000000000000000000000000000",
          "alloc": {
            "23d2B00318eD562931614edc6fCF1B5bF239a2a6": {
              "balance": "90000000000000000000000"
            },
            "102DB1828698E14DCD5E1b37A16E919Fe5e469F0": {
              "balance": "90000000000000000000000"
            }
          }
        },
        "blockchain": {
            "nodes": {
                "generate": true,
                "count": 4
            }
        }
    }
  config.toml: |
    genesis-file="./genesis.json"
    data-path="./data" 
    host-allowlist=["*"]
    min-gas-price=0

    #Peers
    p2p-port=30000
    max-peers=42

    # Mining
    miner-enabled=false
    miner-coinbase="0x23d2B00318eD562931614edc6fCF1B5bF239a2a6"

    #rcp
    rpc-http-enabled=true
    rpc-http-port=8540
    rpc-http-cors-origins=["*"]
    rpc-http-api=[ 'ADMIN', 'ETH', 'NET', 'WEB3', 'CLIQUE', 'IBFT', 'PERM', 'DEBUG', 'MINER', 'EEA', 'PRIV', 'TXPOOL']
    rpc-ws-enabled=true
    rpc-ws-port="6174"
    rpc-ws-api=[ 'ADMIN', 'ETH', 'NET', 'WEB3', 'CLIQUE', 'IBFT', 'PERM', 'DEBUG', 'MINER', 'EEA', 'PRIV', 'TXPOOL']

    # permissions
    permissions-nodes-config-file-enabled=true
    permissions-accounts-config-file-enabled=true
    permissions-nodes-config-file="./data/permissions_config.toml"
    permissions-accounts-config-file="./data/permissions_config.toml"
  permissions_config.toml: |
    accounts-allowlist=["0x23d2B00318eD562931614edc6fCF1B5bF239a2a6","0x102DB1828698E14DCD5E1b37A16E919Fe5e469F0"]
    nodes-allowlist=[]

