apiVersion: apps/v1
kind: Deployment
metadata:
  name: debug-pvc
  namespace: besu-network
spec:
  replicas: 1
  selector:
    matchLabels:
      app: debug-pvc
  template:
    metadata:
      labels:
        app: debug-pvc
    spec:
      containers:
        - name: debug-container
          image: hyperledger/besu:22.10.0-RC2
          command: ["sh", "-c", "sleep 36000"]
          volumeMounts:
            - name: pvcvolume
              mountPath: /mnt/test
          resources:
            limits:
              cpu: "250m"
              memory: "64Mi"
            requests:
              cpu: "100m"
              memory: "32Mi"
      volumes:
        - name: pvcvolume
          persistentVolumeClaim:
            claimName: genesis-network-pvc

