apiVersion: batch/v1
kind: Job
metadata:
  name: genesis-generator
  namespace: besu-network
spec:
  template:
    metadata:
      labels:
        app: genesis-generator
    spec:
      restartPolicy: OnFailure
      initContainers:
        - name: init-copy-config
          image: busybox:latest
          command:
            [
              "sh",
              "-c",
              "cp /config/*.json /mnt/besu-config/ && cp /config/*.toml /mnt/besu-config/",
            ]
          volumeMounts:
            - name: config-files
              mountPath: /config
            - name: generate-network-files
              mountPath: /mnt/besu-config

      containers:
        - name: genesis-generator
          image: hyperledger/besu:22.10.0-RC2
          imagePullPolicy: IfNotPresent
          resources:
            limits:
              cpu: "500m"
              memory: "512Mi"
            requests:
              cpu: "250m"
              memory: "256Mi"
          securityContext:
            runAsUser: 0
          command:
            [
              "/bin/bash",
              "-c",
              "besu operator generate-blockchain-config --config-file=/besu-config/initialGenesis.json --to=/besu-config/networkFiles --private-key-file-name=key",
            ]
          volumeMounts:
            - name: generate-network-files
              mountPath: /besu-config

        - name: rename-keys
          image: python:3.11-slim
          imagePullPolicy: IfNotPresent
          resources:
            limits:
              cpu: "200m"
              memory: "256Mi"
            requests:
              cpu: "100m"
              memory: "128Mi"
          command:
            [
              "/bin/bash",
              "-c",
              "pip install rlp && python /scripts/rename_folders.py"
            ]
          volumeMounts:
            - name: generate-network-files
              mountPath: /besu-config
            - name: rename-script-vol
              mountPath: /scripts

      volumes:
        - name: generate-network-files
          persistentVolumeClaim:
            claimName: genesis-network-pvc
        - name: config-files
          configMap:
            name: genesis-config-files
        - name: rename-script-vol
          configMap:
            name: genesis-config-files
