apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: genesis-network-pvc
  namespace: besu-network
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: standard