apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: list-pods-role
  namespace: besu-network
rules:
- apiGroups: [""]
  resources: ["pods","services"]
  verbs: ["list", "get", "watch"]
