apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: besu-node
  namespace: besu-network
spec:
  serviceName: "besu-node"
  replicas: 4
  selector:
    matchLabels:
      app: besu-node
  template:
    metadata:
      labels:
        app: besu-node
    spec:
      initContainers:
        - name: init-copy-keys
          image: busybox:latest
          command:
            - sh
            - -c
            - |
              # Obtiene el nombre del pod (ejemplo: besu-node-0)
              POD_NAME=$(hostname)
              echo "Pod name is $POD_NAME"
              # Extrae el ordinal del pod
              ORDINAL=$(echo $POD_NAME | awk -F '-' '{print $NF}')
              echo "Ordinal: $ORDINAL"
              # Lista las carpetas dentro de /besu-config/networkFiles/keys (ordenadas alfabéticamente)
              KEY_FOLDERS=$(ls -1 /besu-config/networkFiles/keys)
              i=0
              KEY_FOLDER=""
              for folder in $KEY_FOLDERS; do
                if [ "$i" -eq "$ORDINAL" ]; then
                  KEY_FOLDER=$folder
                  break
                fi
                i=$(($i + 1))
              done
              if [ -z "$KEY_FOLDER" ]; then
                echo "No se encontró carpeta para el ordinal $ORDINAL"
                exit 1
              fi
              echo "Usando carpeta de claves: $KEY_FOLDER"
              mkdir -p /besu-node
              cp -r /besu-config/networkFiles/keys/$KEY_FOLDER /besu-node/keys
              cp /besu-config/networkFiles/genesis.json /besu-node/genesis.json
              cp /besu-config/config.toml /besu-node/config.toml
              mkdir -p /besu-node/data
              cp /besu-config/permissions_config.toml /besu-node/data/permissions_config.toml
          volumeMounts:
            # Monta el PVC que contiene la configuración en la ruta real donde se encuentran los archivos
            - name: genesis-shared
              mountPath: /besu-config
              readOnly: true
            # Monta un volumen emptyDir en /besu-node para almacenar los archivos copiados
            - name: besu-data
              mountPath: /besu-node
      containers:
        - name: besu-node
          image: besu-node:v1.0
          imagePullPolicy: IfNotPresent
          ports:
            - name: rpc
              containerPort: 8540
            - name: peer
              containerPort: 30000
          volumeMounts:
            # Monta el mismo volumen emptyDir para que el contenedor principal acceda a los archivos copiados
            - name: besu-data
              mountPath: /besu-node
      volumes:
        - name: genesis-shared
          persistentVolumeClaim:
            claimName: genesis-network-pvc
        - name: besu-data
          emptyDir: {}
