apiVersion: v1
kind: Service
metadata:
  name: besu-node
  namespace: besu-network
spec:
  clusterIP: None
  selector:
    app: besu-node
  ports:
    - name: peer
      port: 30000       # Puerto que quieres exponer internamente para P2P
      targetPort: peer  # Debe coincidir con "name: peer" del contenedor
    - name: rpc
      port: 8540        # Exposición interna del RPC
      targetPort: rpc   # Debe coincidir con "name: rpc" del contenedor
