apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: besu-node
  namespace: besu-network
spec:
  serviceName: "besu-node"
  replicas: 4
  selector:
    matchLabels:
      app: besu-node
  template:
    metadata:
      labels:
        app: besu-node
    spec:
      initContainers:
        - name: init-copy-keys
          image: busybox:latest
          command:
            - sh
            - -c
            - |
              # Obtiene el nombre del pod (ejemplo: besu-node-0)
              POD_NAME=$(hostname)
              echo "Pod name is $POD_NAME"

              # Extrae el ordinal del pod
              ORDINAL=$(echo $POD_NAME | awk -F '-' '{print $NF}')
              echo "Ordinal: $ORDINAL"

              # Buscar la carpeta que comienza con "<ORDINAL>-"
              KEY_FOLDER=$(find /besu-config/networkFiles/keys -type d -name "$ORDINAL-*")

              if [ -z "$KEY_FOLDER" ]; then
                echo "No se encontró carpeta para el ordinal $ORDINAL"
                exit 1
              fi

              echo "Usando carpeta de claves: $KEY_FOLDER"

              # Crear la estructura de directorios y copiar archivos necesarios
              mkdir -p /besu-node
              cp /besu-config/networkFiles/genesis.json /besu-node/genesis.json
              cp /besu-config/config.toml /besu-node/config.toml

              # Crear el directorio data (si no existe)
              mkdir -p /besu-node/data

              # Copiar los archivos (y subdirectorios) que están dentro de KEY_FOLDER hacia /besu-node/data
              cp -r "$KEY_FOLDER"/* /besu-node/data/

              cp /besu-config/permissions_config.toml /besu-node/data/permissions_config.toml
          volumeMounts:
            # Monta el PVC que contiene la configuración en la ruta real donde se encuentran los archivos
            - name: genesis-shared
              mountPath: /besu-config
              readOnly: true
            # Monta un volumen emptyDir en /besu-node para almacenar los archivos copiados
            - name: besu-data
              mountPath: /besu-node
      containers:
        - name: besu-node
          image: besu-node:v1.0
          imagePullPolicy: IfNotPresent
          ports:
            - name: rpc
              containerPort: 8540
            - name: peer
              containerPort: 30000
          volumeMounts:
            # Monta el mismo volumen emptyDir para que el contenedor principal acceda a los archivos copiados
            - name: besu-data
              mountPath: /besu-node
      volumes:
        - name: genesis-shared
          persistentVolumeClaim:
            claimName: genesis-network-pvc
        - name: besu-data
          emptyDir: {}
