apiVersion: v1
kind: Service
metadata:
  name: blockchain-manager-service
  namespace: besu-network
  labels:
    app: blockchain-manager
spec:
  selector:
    app: blockchain-manager
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
  type: NodePort  # Puedes cambiarlo a LoadBalancer o ClusterIP según tus necesidades
