apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-besu-node-svc
  namespace: {{ .Values.ServiceConfig.namespace }}
spec:
  clusterIP: None
  selector:
    app: {{ .Release.Name }}-besu-node
  ports:
    - name: {{ (index .Values.ServiceConfig.ports 0).name }}
      port: {{ (index .Values.ServiceConfig.ports 0).port }}
      targetPort: {{ (index .Values.ServiceConfig.ports 0).targetPort }}
    - name: {{ (index .Values.ServiceConfig.ports 1).name }}
      port: {{ (index .Values.ServiceConfig.ports 1).port }}
      targetPort: {{ (index .Values.ServiceConfig.ports 1).targetPort }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-besu-node-lb
  namespace: {{ .Values.ServiceConfig.namespace }}
spec:
  type: LoadBalancer
  selector:
    app: {{ .Release.Name }}-besu-node
  ports:
    - name: {{ (index .Values.ServiceConfig.ports 0).name }}
      port: {{ (index .Values.ServiceConfig.ports 0).port }}
      targetPort: {{ (index .Values.ServiceConfig.ports 0).targetPort }}
      protocol: TCP
